### ISSUE TITLE
i can use Improve-my-city for joomla 3.5 ?

### ISSUE THREAD

**Issue by lungkao** [icos-urenio/Improve-my-city#123]
i can use Improve-my-city for joomla 3.5 ?

**Comment by zapresko** [comment]
HI you cannot use improve-my-city  on 3.5.0, because all it's components are for 3x which is 2.5.0. 
How do i know about this, because 3days ago i was trying to load improve-my-city into my joomla 3.5.0 but there is always an error. And for the solution, i am still waiting to hear from other developers, users,

**Comment by itsam** [comment]
Guys this repository is for J2.5, for J3 please visit the new [repo](https://github.com/itsam/imc)
